---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: voor/dehydrated-route53
    tag: latest
inputs:
  - name: certificates

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  ENV_NAME:
  DNS_SUFFIX:
run:
  path: /bin/sh
  dir: 
  args:
    - -c
    - |
        set -eux

        mkdir -p ${PWD}/certificates/${ENV_NAME}.${DNS_SUFFIX}/{chains,certs,accounts}

        echo "${ENV_NAME}.${DNS_SUFFIX} *.${ENV_NAME}.${DNS_SUFFIX} *.pks.${ENV_NAME}.${DNS_SUFFIX} > domain" > ${PWD}/domains.txt

        cat ${PWD}/domains.txt

        echo "DOMAINS_TXT=${PWD}/domains.txt" >> ${PWD}/config
        echo "CHALLENGETYPE=dns-01" >> ${PWD}/config
        echo "HOOK=/home/dehydrated/hook.sh" >> ${PWD}/config
        echo "HOOK_CHAIN=no >> ${PWD}/config
        echo "CHAINCACHE=${PWD}/certificates/${ENV_NAME}.${DNS_SUFFIX}/chains" >> ${PWD}/config
        echo "CERTDIR=${PWD}/certificates/${ENV_NAME}.${DNS_SUFFIX}/certs" >> ${PWD}/config
        echo "ACCOUNTDIR=${PWD}/certificates/${ENV_NAME}.${DNS_SUFFIX}/accounts" >> ${PWD}/config

        cat ${PWD}/config

        /home/dehydrated/dehydrated --accept-terms -c -n -f ${PWD}/config

        tar cvfz certificates/certificates.tgz certificates/${ENV_NAME}.${DNS_SUFFIX}/