az-configuration:
{{range (ds "data").azs}}- name: {{.}}
{{end}}
properties-configuration:
  director_configuration:
    ntp_servers_string: 169.254.169.123
    resurrector_enabled: true
    post_deploy_enabled: true
    retry_bosh_deploys: true
{{if index (ds "data") "ssl_cert"}}
  security_configuration:
    trusted_certificates: |
{{indent 6 (ds "data").ssl_cert}}
{{end}}
  iaas_configuration:
    iam_instance_profile: {{(ds "data").ops_manager_iam_instance_profile_name}}
    vpc_id: {{(ds "data").vpc_id}}
    security_group: {{(ds "data").vms_security_group_id}}
    key_pair_name: {{(ds "data").ops_manager_ssh_public_key_name}}
    ssh_private_key: |
{{ indent 6 (ds "data").ops_manager_ssh_private_key }}
    region: {{(ds "data").region}}
network-assignment:
  network:
    name: infrastructure
  singleton_availability_zone:
    name: {{index (ds "data").azs 0}}
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    {{range $i, $a := (ds "data").infrastructure_subnet_cidrs}}
    - availability_zone_names:
      - {{index (ds "data").azs $i}}
      cidr: {{index (ds "data").infrastructure_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index (ds "data").infrastructure_subnet_gateways $i}}
      iaas_identifier: {{index (ds "data").infrastructure_subnet_ids $i}}
      reserved_ip_ranges:  {{ $gateway := index (ds "data").infrastructure_subnet_gateways $i }}{{$gateway}}-{{ $gateway_arr := split $gateway "." }}{{ index $gateway_arr 0 }}.{{ index $gateway_arr 1 }}.{{ index $gateway_arr 2 }}.{{ add (index $gateway_arr 3) 4 }}
    {{end}}
{{if index (ds "data") "pas_subnet_cidrs"}}
  - name: pas
    subnets:
    {{range $i, $a := (ds "data").pas_subnet_cidrs}}
    - availability_zone_names:
      - {{index (ds "data").azs $i}}
      cidr: {{index (ds "data").pas_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index (ds "data").pas_subnet_gateways $i}}
      iaas_identifier: {{index (ds "data").pas_subnet_ids $i}}
      reserved_ip_ranges: {{ $gateway := index (ds "data").pas_subnet_gateways $i }}{{$gateway}}-{{ $gateway_arr := split $gateway "." }}{{ index $gateway_arr 0 }}.{{ index $gateway_arr 1 }}.{{ index $gateway_arr 2 }}.{{ add (index $gateway_arr 3) 4 }}
    {{end}}
{{end}}
{{if index (ds "data") "pks_subnet_cidrs"}}
  - name: pks
    subnets:
    {{range $i, $a := (ds "data").pks_subnet_cidrs}}
    - availability_zone_names:
      - {{index (ds "data").azs $i}}
      cidr: {{index (ds "data").pks_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index (ds "data").pks_subnet_gateways $i}}
      iaas_identifier: {{index (ds "data").pks_subnet_ids $i}}
      reserved_ip_ranges: {{ $gateway := index (ds "data").pks_subnet_gateways $i }}{{$gateway}}-{{ $gateway_arr := split $gateway "." }}{{ index $gateway_arr 0 }}.{{ index $gateway_arr 1 }}.{{ index $gateway_arr 2 }}.{{ add (index $gateway_arr 3) 4 }}
    {{end}}
{{end}}
{{if index (ds "data") "control_plane_subnet_cidrs" }}
  - name: control-plane
    subnets:
    {{range $i, $a := (ds "data").control_plane_subnet_cidrs}}
    - availability_zone_names:
        - {{index (ds "data").azs $i}}
      cidr: {{index (ds "data").control_plane_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index (ds "data").control_plane_subnet_gateways $i}}
      iaas_identifier: {{index (ds "data").control_plane_subnet_ids $i}}
      # FIXME: This won't work, because by default our subnets are smaller for control plane.
      reserved_ip_ranges: {{ $gateway := index (ds "data").control_plane_subnet_cidrs $i }}{{$gateway}}-{{ $gateway_arr := split $gateway "." }}{{ index $gateway_arr 0 }}.{{ index $gateway_arr 1 }}.{{ index $gateway_arr 2 }}.{{ add (index $gateway_arr 3) 4 }}
    {{end}}
{{else}}
  - name: services
    subnets:
    {{range $i, $a := (ds "data").services_subnet_cidrs}}
    - availability_zone_names:
        - {{index (ds "data").azs $i}}
      cidr: {{index (ds "data").services_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index (ds "data").services_subnet_gateways $i}}
      iaas_identifier: {{index (ds "data").services_subnet_ids $i}}
      reserved_ip_ranges: {{ $gateway := index (ds "data").services_subnet_gateways $i }}{{$gateway}}-{{ $gateway_arr := split $gateway "." }}{{ index $gateway_arr 0 }}.{{ index $gateway_arr 1 }}.{{ index $gateway_arr 2 }}.{{ add (index $gateway_arr 3) 4 }}
    {{end}}
{{end}}
resource-configuration:
  compilation:
    instance_type:
      id: c5.xlarge
vmextensions-configuration:
  - name: pks-api-lb-security-groups
    cloud_properties:
      security_groups: ["pks_api_lb_security_group", "vms_security_group"]
  - name: harbor-api-lb-security-groups
    cloud_properties:
      security_groups: [{{ (ds "data").harbor_lb_security_group | quote }}, "vms_security_group"]
      iam_instance_profile: {{ (ds "data").harbor_profile_name }}
  - name: compliance-scanner-instance-profile
    cloud_properties:
      security_groups: ["vms_security_group"]
      iam_instance_profile: {{ (ds "data").compliance_scanner_profile_name }}